# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='선택틀',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('선택지', models.CharField(max_length=200)),
                ('투표수', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='질문틀',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('질문내용', models.CharField(max_length=200)),
                ('질문날짜', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='선택틀',
            name='관련질문',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.질문틀'),
        ),
    ]
